### PR TITLE
[CLOUD-2591] Changed standalone image to install jdg client

### PR DESCRIPTION
**Pull request by vhalbert**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by vhalbert** [comment]
Changed from using JDV 6.4.3 to 6.4.2.

**Comment by vhalbert** [comment]
Need reviews.

**Comment by jrenaat** [comment]
The changes look ok, although they only seem to be about including the jdg client in the standalone image, i.e. I don't see any related to the reversion back to DV 6.4.2?

**Comment by vhalbert** [comment]
The original PR was using 6.4.3, I amended the PR so that its using 6.4.2.  And because those values are not different, they don't show up as being changed.

**Review by jrenaat — APPROVED** [review]
Looks good to me

**Pull request merged**
